"""initial schema

Revision ID: 5ba2446fa7ea
Revises:
Create Date: 2026-06-05 19:25:10.658006

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5ba2446fa7ea'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('root_path', sa.String(length=1024), nullable=False),
    sa.Column('include_patterns', sqlite.JSON(), nullable=False),
    sa.Column('exclude_patterns', sqlite.JSON(), nullable=False),
    sa.Column('respect_gitignore', sa.Boolean(), nullable=False),
    sa.Column('max_file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('follow_symlinks', sa.Boolean(), nullable=False),
    sa.Column('llm_provider', sa.String(length=100), nullable=True),
    sa.Column('llm_model', sa.String(length=255), nullable=True),
    sa.Column('llm_parameters', sqlite.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('processing_jobs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('files_processed', sa.Integer(), nullable=False),
    sa.Column('files_total', sa.Integer(), nullable=False),
    sa.Column('errors', sqlite.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('cancel_requested_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processing_jobs')
    op.drop_table('projects')
    # ### end Alembic commands ###
